server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    # Explicitly block any requests to the backend API prefix
    location /CineMatch {
        return 404;
    }
}
