services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinematch-frontend
    ports:
      - "4200:80"
    networks:
      - cinematch-net
    depends_on:
      - gateway
      - core 

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: cinematch-gateway
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ./gateway/.env
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command: sh -c "npx prisma migrate deploy && node dist/server.js"
    ports:
      - "3001:3000"
    depends_on:
      users_db:
        condition: service_healthy
      core:
        condition: service_started
      s3-storage:
        condition: service_started
    networks:
      - cinematch-net

  core:
    build: ./core
    container_name: cinematch-core
    working_dir: /app
    env_file:
      - ./core/.env
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*'"
    ports:
      - "8000:8000"
    networks:
      - cinematch-net
    depends_on:
      movies_db:
        condition: service_healthy

  movies_db:
    image: postgres:15-alpine
    container_name: cinematch-movies-postgres
    restart: always
    environment:
      POSTGRES_USER: cinematch_movies_admin
      POSTGRES_PASSWORD: cinematch_movies_password
      POSTGRES_DB: cinematch_movies_db
      POSTGRES_HOST: movies_db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-movies-data:/var/lib/postgresql/data
    command: >
      sh -c "apk add --no-cache openssl
      && openssl req -new -x509 -days 365 -nodes -text -out /tmp/server.crt -keyout /tmp/server.key -subj '/CN=movies_db'
      && chmod 600 /tmp/server.key
      && chown postgres:postgres /tmp/server.key /tmp/server.crt
      && exec docker-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/tmp/server.crt -c ssl_key_file=/tmp/server.key"
    networks:
      - cinematch-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinematch_movies_admin -d cinematch_movies_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  users_db:
    image: postgres:15-alpine
    container_name: cinematch-users-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: cinematch_users_admin
      POSTGRES_PASSWORD: cinematch_users_password
      POSTGRES_DB: cinematch_users_db
    ports:
      - "5433:5432"
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
    command: >
      sh -c "apk add --no-cache openssl
      && openssl req -new -x509 -days 365 -nodes -text -out /tmp/server.crt -keyout /tmp/server.key -subj '/CN=users_db'
      && chmod 600 /tmp/server.key
      && chown postgres:postgres /tmp/server.key /tmp/server.crt
      && exec docker-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/tmp/server.crt -c ssl_key_file=/tmp/server.key"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinematch_users_admin -d cinematch_users_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - cinematch-net

  # S3 Compatible Object Storage
  s3-storage:
    image: minio/minio:latest
    container_name: cinematch-s3
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    ports:
      - "9000:9000" # API Port (FastAPI and Frontend talk to this)
      - "9001:9001" # Web UI Port (For browser)
    command: server /data --console-address ":9001"
    volumes:
      - s3-data:/data
    networks:
      - cinematch-net

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cinematch-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmq_admin
      RABBITMQ_DEFAULT_PASS: rmq_password
      RABBITMQ_DEFAULT_VHOST: rmq_admin
    ports:
      - "5672:5672"   # AMQP protocol port (FastAPI talks to this)
      - "15672:15672" # Web UI port (For browser)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - cinematch-net
    healthcheck:                                            
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]   
      interval: 5s                                         
      timeout: 5s                                          
      retries: 10

  # AI recommendation service 
  ai-recommender:
    build:
      context: ./AI recommendation
      dockerfile: Dockerfile
    container_name: cinematch-ai-recommender
    working_dir: /app
    env_file:
      - ./AI recommendation/.env
    ports:
      - "8001:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cinematch-net
      

  # AI review summarizer worker
  review-summary-ai:
    build:
      context: ./review-summary-ai
      dockerfile: Dockerfile
    container_name: cinematch-review-summary-ai
    working_dir: /app
    env_file:
      - ./review-summary-ai/.env
    ports:
      - "8002:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - cinematch-net

networks:
  cinematch-net:
    driver: bridge

volumes:
  postgres-movies-data:
  users-postgres-data:
  s3-data:
  rabbitmq-data:
