from typing import Literal

from pydantic import BaseModel, Field, field_validator

from schemas.tmdbmovie import TmdbMovie


class AISearchRequest(BaseModel):
    """
    Schema for the AI-powered movie search request.
    """

    # The natural language query from the user
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="The natural language movie prompt",
    )


class AIFilters(BaseModel):
    """
    Detailed filters generated by the AI to be used with the TMDB API.
    """

    certification: str | None = Field(None, description="Movie certification (e.g., PG-13)")
    language: str | None = Field(None, description="ISO 639-1 language code for translations (the 'language' parameter)")
    original_language: str | None = Field(None, 
        description="ISO 639-1 language code to filter by original language (the 'with_original_language' parameter)")
    with_genres: list[int] = Field(default_factory=list, description="List of genre IDs to include")
    without_genres: list[int] = Field(default_factory=list, description="List of genre IDs to exclude")
    with_cast: list[int | str] = Field(default_factory=list, description="List of actor IDs or names to include")
    with_crew: list[int | str] = Field(default_factory=list, description="List of crew IDs or names to include")
    year: int | None = Field(None, description="Release year")
    primary_release_year: int | None = Field(None, description="Primary release year")
    primary_release_date_gte: str | None = Field(None, description="Release date greater than or equal to (YYYY-MM-DD)")
    primary_release_date_lte: str | None = Field(None, description="Release date less than or equal to (YYYY-MM-DD)")
    release_date_gte: str | None = Field(None, description="Release date greater than or equal to (YYYY-MM-DD)")
    release_date_lte: str | None = Field(None, description="Release date less than or equal to (YYYY-MM-DD)")
    with_runtime_gte: int | None = Field(None, description="Minimum runtime in minutes")
    with_runtime_lte: int | None = Field(None, description="Maximum runtime in minutes")
    vote_average_gte: float | None = Field(None, description="Minimum average vote score")
    vote_average_lte: float | None = Field(None, description="Maximum average vote score")
    vote_count_gte: int | None = Field(100, description="Minimum number of votes (defaults to 100 to ensure rating reliability)")
    vote_count_lte: int | None = Field(None, description="Maximum number of votes")
    sort_by: str | None = Field(None, description="Sorting criteria")
    include_adult: bool = Field(False, description="Whether to include adult content")
    query: str | None = Field(None, description="Search query string for search mode")

    @field_validator("vote_count_gte", mode="before")
    @classmethod
    def set_default_vote_count(cls, v: int | None) -> int:
        """
        Ensures vote_count_gte defaults to 100 if it is None or missing.
        """
        return v if v is not None else 100


class AISearchResponse(BaseModel):
    """
    Schema for the AI-powered movie search response.
    Contains the operational mode and the generated filters.
    """

    mode: str = Field(..., description="The search mode (e.g., 'discover' or 'search')")
    filters: AIFilters = Field(..., description="The filters extracted by the AI")
    fallback_reason: str | None = Field(
        None, description="Reason for falling back to default results, if any"
    )

class AISearchSuccess(BaseModel):
    """Schema for a successful AI movie search."""
    # Literal locks this exact string. It can ONLY ever be "success"
    status: Literal["success"] = Field("success", description="Indicates a successful AI search")
    fallback_used: Literal[False] = Field(False, description="No fallback was needed")
    
    movies: list[TmdbMovie] = Field(
        ..., 
        description="A list of movie results discovered by the AI search filters"
    )

class AISearchFallback(BaseModel):
    """Schema for when the AI fails and triggers a fallback."""
    status: Literal["fallback"] = Field("fallback", description="Indicates the AI search failed")
    fallback_used: Literal[True] = Field(True, description="A fallback search is required")
    
    
    original_prompt: str = Field(
        ..., 
        description="The original user prompt that triggered the AI search"
    )
    error_detail: str = Field(
        ..., 
        description="Detail about why a fallback search was triggered"
    )

