"""Add ReviewSummary

Revision ID: 2c5d1e8c243a
Revises: 182e276718ea
Create Date: 2026-03-18 13:57:18.744226

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c5d1e8c243a'
down_revision: Union[str, Sequence[str], None] = '182e276718ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_summaries_id'), 'review_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_review_summaries_tmdb_id'), 'review_summaries', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_summaries_tmdb_id'), table_name='review_summaries')
    op.drop_index(op.f('ix_review_summaries_id'), table_name='review_summaries')
    op.drop_table('review_summaries')
    # ### end Alembic commands ###
