apiVersion: v1
kind: Service
metadata:
  name: cinematch-ai-recommender
spec:
  type: ClusterIP
  selector:
    app: cinematch-ai-recommender
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
