apiVersion: v1
kind: Service
metadata:
  name: cinematch-frontend
spec:
  type: LoadBalancer
  selector:
    app: cinematch-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
