apiVersion: v1
kind: Service
metadata:
  name: cinematch-gateway
spec:
  type: LoadBalancer
  selector:
    app: cinematch-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
