apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - movies-postgres.yaml
  - users-postgres.yaml
  - rabbitmq.yaml
  - minio.yaml

secretGenerator:
  - name: gateway-env-secret
    envs:
      - gateway.env
  - name: core-env-secret
    envs:
      - core.env
  - name: review-summary-ai-env-secret
    envs:
      - review-summary-ai.env
  - name: ai-recommender-env-secret
    envs:
      - ai-recommender.env
