apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinematch-users-db
  labels:
    app: cinematch-users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinematch-users-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cinematch-users-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "cinematch_users_admin"
        - name: POSTGRES_PASSWORD
          value: "cinematch_users_password"
        - name: POSTGRES_DB
          value: "cinematch_users_db"
        volumeMounts:
        - name: users-postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: users-postgres-data
        persistentVolumeClaim:
          claimName: postgres-users-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  type: LoadBalancer
  selector:
    app: cinematch-users-db
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432
